In [2]:
import matplotlib.pyplot as plt
import numpy as np

In [3]:
fig = plt.figure()

<Figure size 640x480 with 0 Axes>

In [4]:
ax = fig.add_subplot(projection='3d')

In [5]:
X = np.arange(-5, 5, 0.15)
Y = np.arange(-5, 5, 0.15)

In [6]:
X

array([-5.  , -4.85, -4.7 , -4.55, -4.4 , -4.25, -4.1 , -3.95, -3.8 ,
       -3.65, -3.5 , -3.35, -3.2 , -3.05, -2.9 , -2.75, -2.6 , -2.45,
       -2.3 , -2.15, -2.  , -1.85, -1.7 , -1.55, -1.4 , -1.25, -1.1 ,
       -0.95, -0.8 , -0.65, -0.5 , -0.35, -0.2 , -0.05,  0.1 ,  0.25,
        0.4 ,  0.55,  0.7 ,  0.85,  1.  ,  1.15,  1.3 ,  1.45,  1.6 ,
        1.75,  1.9 ,  2.05,  2.2 ,  2.35,  2.5 ,  2.65,  2.8 ,  2.95,
        3.1 ,  3.25,  3.4 ,  3.55,  3.7 ,  3.85,  4.  ,  4.15,  4.3 ,
        4.45,  4.6 ,  4.75,  4.9 ])

In [7]:

X, Y = np.meshgrid(X, Y)

In [8]:
X

array([[-5.  , -4.85, -4.7 , ...,  4.6 ,  4.75,  4.9 ],
       [-5.  , -4.85, -4.7 , ...,  4.6 ,  4.75,  4.9 ],
       [-5.  , -4.85, -4.7 , ...,  4.6 ,  4.75,  4.9 ],
       ...,
       [-5.  , -4.85, -4.7 , ...,  4.6 ,  4.75,  4.9 ],
       [-5.  , -4.85, -4.7 , ...,  4.6 ,  4.75,  4.9 ],
       [-5.  , -4.85, -4.7 , ...,  4.6 ,  4.75,  4.9 ]])

In [9]:
Y

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.85, -4.85, -4.85, ..., -4.85, -4.85, -4.85],
       [-4.7 , -4.7 , -4.7 , ..., -4.7 , -4.7 , -4.7 ],
       ...,
       [ 4.6 ,  4.6 ,  4.6 , ...,  4.6 ,  4.6 ,  4.6 ],
       [ 4.75,  4.75,  4.75, ...,  4.75,  4.75,  4.75],
       [ 4.9 ,  4.9 ,  4.9 , ...,  4.9 ,  4.9 ,  4.9 ]])

In [10]:
R = np.sqrt(X ** 2 + Y ** 2)

In [11]:
R

array([[7.07106781, 6.96580936, 6.86221539, ..., 6.7941151 , 6.89655711,
        7.00071425],
       [6.96580936, 6.85893578, 6.75370269, ..., 6.68449699, 6.78859337,
        6.89438177],
       [6.86221539, 6.75370269, 6.64680374, ..., 6.57647322, 6.68225261,
        6.78969808],
       ...,
       [6.7941151 , 6.68449699, 6.57647322, ..., 6.50538239, 6.61229915,
        6.72086304],
       [6.89655711, 6.78859337, 6.68225261, ..., 6.61229915, 6.71751442,
        6.82440474],
       [7.00071425, 6.89438177, 6.78969808, ..., 6.72086304, 6.82440474,
        6.92964646]])

In [12]:
Z = np.sin(R)

In [13]:
ax.plot_surface(X, Y, Z, rstride=1, cstride=1, cmap="viridis")  

<Axes3D: >