In [1]:
import numpy as np

In [2]:
print (np.__version__)

1.26.4


In [3]:
# 1D Array

In [6]:
a = np.array([1, 2, 3, 4, 5])

In [7]:
type(a) 

numpy.ndarray

In [8]:
a * 2

array([ 2,  4,  6,  8, 10])

In [9]:
a * 10000

array([10000, 20000, 30000, 40000, 50000])

In [10]:
# ^^^ This is called Vectorization

In [11]:
a[0]

1

In [15]:
# Types of Arrays 
# 1D array, 2D array, ndarray, vector, matrix

In [18]:
# 1D -> Vector
# 2D -> Matrix
# >= 3D -> Tensor

In [21]:
# Vectors
# np.array(), np.zeros(), np.ones(), np.empty(), np.arange(), np.linspace(), dtype

In [23]:
arr = np.array([1, 2, 3])

In [24]:
arr

array([1, 2, 3])

In [26]:
z0 = np.zeros(10)

In [27]:
z0

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [28]:
z1 = np.ones(10)

In [29]:
z1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [38]:
empty = np.empty(11)
empty

array([nan,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [39]:
# Range of elements

In [40]:
r = np.arange(10)

In [41]:
r

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
# from i to j with r at a time

In [43]:
np.arange(1, 100, 25)

array([ 1, 26, 51, 76])

In [44]:
# Specifying Datatypes

In [45]:
array = np.ones(100, dtype=np.int64)

In [46]:
# Operations

In [47]:
arr = np.empty(100)

In [48]:
arr

array([0.00000000e+000, 0.00000000e+000, 4.94065646e-324, 6.95273041e-310,
       4.69362364e-322, 1.12650236e-311, 1.12650236e-311, 1.12650236e-311,
       1.12650236e-311, 1.12650579e-311, 1.12650236e-311, 1.12650236e-311,
       1.12650236e-311, 1.12650236e-311, 1.12650579e-311, 1.12650236e-311,
       1.12650236e-311, 1.12650236e-311, 1.12650236e-311, 1.12650236e-311,
       1.12650579e-311, 1.12650236e-311, 1.12650236e-311, 1.12650236e-311,
       1.12650236e-311, 1.12650236e-311, 1.12650236e-311, 1.12650578e-311,
       1.12650236e-311, 1.12650236e-311, 1.12650236e-311, 1.12650236e-311,
       1.12650236e-311, 1.12650236e-311, 1.12650236e-311, 1.12650579e-311,
       1.12650236e-311, 1.12650236e-311, 1.12650236e-311, 1.12650578e-311,
       1.12650236e-311, 1.12650236e-311, 1.12650236e-311, 1.12650236e-311,
       1.12650236e-311, 1.12650236e-311, 1.12650236e-311, 1.12650236e-311,
       1.12650236e-311, 1.12650236e-311, 1.12650236e-311, 1.12650236e-311,
       1.12650236e-311, 1

In [49]:
np.sort(arr)

array([0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 4.94065646e-324, 4.69362364e-322,
       1.12650236e-311, 1.12650236e-311, 1.12650236e-311, 1.12650236e-311,
       1.12650236e-311, 1.12650236e-311, 1.12650236e-311, 1.12650236e-311,
       1.12650236e-311, 1.12650236e-311, 1.12650236e-311, 1.12650236e-311,
       1.12650236e-311, 1.12650236e-311, 1.12650236e-311, 1.12650236e-311,
       1.12650236e-311, 1.12650236e-311, 1.12650236e-311, 1.12650236e-311,
       1.12650236e-311, 1.12650236e-311, 1.12650236e-311, 1.12650236e-311,
       1.12650236e-311, 1.12650236e-311, 1.12650236e-311, 1.12650236e-311,
       1.12650236e-311, 1

In [ ]:
# Numpy also have concatenate

In [51]:
# Shape and size of array
#  ndarray.ndim, ndarray.size, ndarray.shape

In [52]:
arra = np.array([[1, 2], [3, 4], [5, 6]])

In [53]:
arra

array([[1, 2],
       [3, 4],
       [5, 6]])

In [54]:
arra.ndim

2

In [55]:
arra.size

6

In [56]:
arra.shape

(3, 2)

In [57]:
# Shape is M X N X K for 3D
# Reshaping Aray

In [58]:
arra

array([[1, 2],
       [3, 4],
       [5, 6]])

In [59]:
arra.shape

(3, 2)

In [62]:
arra.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
arra.T

array([[1, 3, 5],
       [2, 4, 6]])

In [64]:
arr1d = np.array([1, 2, 3])

In [65]:
# Concat arr1d (1D array) into arra (2D array)

In [68]:
arr1d[3]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [69]:
arr1d[1]

2

In [70]:
arr1d[arr1d >= 2]

array([2, 3])

In [71]:
arra

array([[1, 2],
       [3, 4],
       [5, 6]])

In [72]:
arra.sum()

21

In [73]:
arra.sum(axis=1)

array([ 3,  7, 11])

In [74]:
arra.sum(axis=0)

array([ 9, 12])

In [75]:
# Matrix

In [77]:
mat = np.array([[1, 2], [3, 4], [5, 6]])
mat.shape

(3, 2)

In [78]:
mat.T

array([[1, 3, 5],
       [2, 4, 6]])

In [79]:
mat.T.shape

(2, 3)

In [83]:
a = np.array([1, 2, 3])

In [84]:
np.flip(a)

array([3, 2, 1])